version: "3.7"
services:

  postgres:
    image: postgres
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin12345
      - POSTGRES_DB=controleproducao
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    volumes:
      - ./.postgres-data/pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"